export const DIATY_ENTRIES = 'DIATY_ENTRIES';
export const DIATY_ENTRIES_SUCCESS = 'DIATY_ENTRIES_SUCCESS';
export const DIATY_ENTRIES_ERROR = 'DIATY_ENTRIES_ERROR';
export const DIATY_ENTRIES__CLEAR = 'DIATY_ENTRIES__CLEAR';

export const DIATY_ENTRIES_GET = 'DIATY_ENTRIES_GET';
export const DIATY_ENTRIES_GET_SUCCESS = 'DIATY_ENTRIES_GET_SUCCESS';
export const DIATY_ENTRIES_GET_ERROR = 'DIATY_ENTRIES_GET_ERROR';

export const DIATY_ENTRIES_CREATE = 'DIATY_ENTRIES_CREATE';
export const DIATY_ENTRIES_CREATE_SUCCESS = 'DIATY_ENTRIES_CREATE_SUCCESS';
export const DIATY_ENTRIES_CREATE_ERROR = 'DIATY_ENTRIES_CREATE_ERROR';

export const DIATY_ENTRIES_UPDATE = 'DIATY_ENTRIES_UPDATE';
export const DIATY_ENTRIES_UPDATE_SUCCESS = 'DIATY_ENTRIES_UPDATE_SUCCESS';
export const DIATY_ENTRIES_UPDATE_ERROR = 'DIATY_ENTRIES_UPDATE_ERROR';
